make:	cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/GameBoard.java
	javac cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/GameBoard.java

run:	#cpsc2150/connectX/src/cpsc2150/connectX/Connect4Game.class cpsc2150/connectX/src/cpsc2150/connectX/GameBoard.class
	java cpsc2150.connectX.Connect4Game cpsc2150.connectX.GameBoard
	
clean:
	rm -f *.class
	
