make:	cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/GameBoard.java cpsc2150/connectX/IGameBoard.java
	javac cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/GameBoard.java cpsc2150/connectX/IGameBoard.java

run:	cpsc2150/connectX/Connect4Game.class cpsc2150/connectX/GameBoard.class cpsc2150/connectX/IGameBoard.class
	java cpsc2150.connectX.Connect4Game cpsc2150.connectX.GameBoard cpsc2150.connectX.IGameBoard
	
clean:
	rm -f *.class
	
